### ESP32 used is a ESP2-WROOM-32S

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# uart for modbus rtu
uart:
  id: mod_bus
  baud_rate: 9600
  stop_bits: 1
  tx_pin: 19
  rx_pin: 23

# i2c for extra sensor
#i2c:  
#  sda: 21
#  scl: 22
#  scan: true
#  id: bus_a

# Enable/Disable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${name}"
    password: "configesp"

captive_portal:

# Enable Web server.
web_server:
  port: 80

ota:
